name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

# Nadaj uprawnienia GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Pozwól tylko jeden deployment na raz
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination ./_site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      # Opcjonalny krok - jawne skopiowanie assets jeśli Jekyll ich nie kopiuje
      - name: Copy assets
        run: |
          if [ -d "assets" ]; then
            echo "Copying assets directory..."
            mkdir -p ./assets
            cp -r assets/* ./assets/
            echo "Assets copied successfully:"
            ls -la ./assets/
          fi
          if [ -d "images" ]; then
            echo "Copying images directory..."
            mkdir -p ./_site/images
            cp -r images/* ./_site/images/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4