name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Zaktualizowana wersja
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}  # Poprawna składnia
          target_branch: gh-pages
          pre_build_commands: |
            gem update --system
            bundle config set --local deployment 'false'
            bundle config set --local path 'vendor/bundle'
            # Alternatywnie, jeśli powyższe nie zadziała:
            # gem install ffi -v '~> 1.16.0'